#!/usr/bin/env bash
set -euo pipefail

# TradeTracker scope guard – dokumentációs állapot validálása.

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
DOC_PATH="${ROOT_DIR}/impactshop-notes/TradeTracker-integráció.md"
REPORT_DIR="${ROOT_DIR}/.codex/reports/tradetracker"
REPORT_FILE="${REPORT_DIR}/scope-overview.md"

mkdir -p "${REPORT_DIR}"

ts="$(date '+%Y-%m-%d %H:%M:%S')"

if [[ ! -f "${DOC_PATH}" ]]; then
  echo "❌ Hiányzó dokumentum: ${DOC_PATH}"
  exit 1
fi

echo "✅ Dokumentum megtalálva: ${DOC_PATH}"

cat >"${REPORT_FILE}" <<EOF
# TradeTracker scope overview
_Generated by tradetracker-scope-check.sh @ ${ts}_

- Source doc: impactshop-notes/TradeTracker-integráció.md
- Status   : Planning (no production impact)
- Next step: create scaffold under impact-bridge-tradetracker/ before implementation.

## Follow-up checklist
- [ ] Könyvtárstruktúra létrehozva a repo gyökerében
- [ ] Konfigurációs értékek vaultban (TT_CUSTOMER_ID, TT_PASSPHRASE)
- [ ] Guardrail szkriptek ("scripts/diagnostics/tt_*.sh") megírva
- [ ] Impact router "/go" módosítás tervezet felülvizsgálva
- [ ] Tesztterv finomhangolva (unit + integration + smoke)
- [ ] Rollback folyamat szimulálva (dry-run)

EOF

echo "📄 Report frissítve: ${REPORT_FILE}"
